services:
  - type: web
    name: cnn-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api_cnn:app --config gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0